export const RANDOM_FIXTURES = 'RANDOM_FIXTURES';
export const TODAY_fIXTURES = 'TODAY_FIXTURES';
export const TOMORROW_FIXTURES = 'TOMORROW_FIXTURES';
export const NEXT_TOMORROW_FIXTURES = 'NEXT_TOMORROW_FIXTURES';